ALTER TABLE users
ADD COLUMN IF NOT EXISTS role VARCHAR(20) NOT NULL DEFAULT 'user';

ALTER TABLE users
DROP CONSTRAINT IF EXISTS users_role_check;

ALTER TABLE users
ADD CONSTRAINT users_role_check CHECK (role IN ('user', 'admin'));

ALTER TABLE technologies
ADD COLUMN IF NOT EXISTS description TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS best_for TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS risk_notes TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS alternatives TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS docs_url TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
